namespace EazyHttp.Generator.Generators;

[Generator]
internal sealed class DiRegistrationGenerator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.RegisterPostInitializationOutput(static ctx =>
    {
      var code = $"""
        {AutoGeneratedComment}
        global using {nameof(EazyHttp)}.{Generated}.{DependencyInjection};
        """;
      
      ctx.AddSource("DiRegistrationGlobalUsings.g.cs", code);
    });

    context.DefaultSourceOutputRegistration(Execute);
  }

  private static void Execute(
    SourceProductionContext context,
    ImmutableArray<EazyClientOptionsDefinition> options,
    bool nullableEnabled)
  {
    if (options.IsDefaultOrEmpty)
    {
      return;
    }

    foreach (var o in options)
    {
      GenerateClientsRegistration(context, o, nullableEnabled);
    }
  }

  private static void GenerateClientsRegistration(
    SourceProductionContext context,
    EazyClientOptionsDefinition options,
    bool nullableEnabled)
  {
    var code = $$"""
      {{AutoGeneratedComment}}
      {{nullableEnabled.ToNullableDirectiveIfEnabled()}}
      
      {{GetUsings(options)}}
      
      namespace {{nameof(EazyHttp)}}.{{Generated}}.{{DependencyInjection}};

      public static class {{options.GetNameByNamespace()}}DiRegistration
      {
        public static IServiceCollection {{options.GetNameByNamespace()}}(this IServiceCollection services)
        {
          {{GetClientsRegistrations(options)}}

          return services;
        }

        {{GetResolverMethods(nullableEnabled)}}
      }
      """;

    context.AddSource(
      options.GetDiRegistrationFilename(),
      code.GetFormattedCode());
  }

  private static string GetClientsRegistrations(
    EazyClientOptionsDefinition options)
  {
    var sb = new StringBuilder();

    foreach (var client in options.Clients)
    {
      var handlerSb = new StringBuilder();
      var retrySb = new StringBuilder();

      sb.AppendLine("services");
      
      sb.AppendLine(
        $".AddHttpClient<I{client.Name}, {client.Name}>(\"{client.Name}\")");

      AppendRetryPolicyonfiguration(
        retrySb,
        client);

      AppendHandlerConfiguration(
        handlerSb,
        options,
        client);

      sb.AppendLine($"{retrySb}");
      sb.AppendLine($"{handlerSb};");
    }

    return sb.ToString();
  }

  private static string GetUsings(EazyClientOptionsDefinition options)
  {
    string[] namespaces =
    [
      "Microsoft.Extensions.DependencyInjection",
      options
        .NamespacePrefix
        .GetEazyHttpClientNamespace(),
      "Polly",
      $"{nameof(EazyHttp)}.Runtime",
      $"{nameof(EazyHttp)}.{nameof(Contracts)}",
      $"{nameof(EazyHttp)}.{nameof(Configuration)}",
      "Microsoft.Extensions.Options",
      "System.Net.Http"
    ];

    var sb = new StringBuilder();

    foreach (var ns in namespaces.OrderBy(x => x))
    {
      sb.AppendLine($"using {ns};");
    }

    return sb.ToString();
  }

  private static void AppendHandlerConfiguration(
    StringBuilder sb,
    EazyClientOptionsDefinition options,
    HttpClientDefinition client)
  {
    if (options.HttpClientHandlers.TryGetValue(
        client.Name,
        out var handlerDefinition))
    {
      var handlerName = handlerDefinition
        .TypeExpression
        .TryGetHandlerTypeName();

      var method = "AddHttpMessageHandler";

      if (handlerDefinition.IsPrimary)
      {
        method = "ConfigurePrimaryHttpMessageHandler";
      }

      sb.AppendLine(
        $".{method}<{handlerName}>();");

      sb.AppendLine("services");

      sb.AppendLine(
        $".AddTransient<{handlerName}>()");
    }
  }

  private static void AppendRetryPolicyonfiguration(
    StringBuilder sb,
    HttpClientDefinition client)
  {
    var code = $$"""
      .AddPolicyHandler((sp, request) =>
      {
        var eazyOptions = sp
          .GetRequiredService<IOptions<EazyClientOptions>>()
          .Value;

        var context = new ClientContext(
          nameof({{client.Name}}), 
          sp);

        var retryConfig = ResolveRetry(
          context,
          eazyOptions);

        return HttpRetryExecutor.CreatePolicy(retryConfig);
      })
      """;

    sb.AppendLine(code);
  }

  private static string GetResolverMethods(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private static RetryConfiguration{{nullable}} ResolveRetry(
        ClientContext context,
        EazyClientOptions options)
      {
        // 1. Fixed per-client retry-config
        if (options.Retries.TryGetValue(context.ClientName, out var cfg))
        {
          return cfg;
        }

        // 2. Resolver fallback
        if (options.ResolveRetry is { } resolver)
        {
          return resolver(context);
        }

        // 3. Default: no retry
        return null;
      }
      """;

    return code;
  }
}
