using Microsoft.CodeAnalysis;
using System.ComponentModel.Design;

namespace EazyHttp.Generator.Generators;

[Generator]
internal sealed class DiRegistrationGenerator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.DefaultSourceOutputRegistration(Execute);
  }

  private static void Execute(
    SourceProductionContext context,
    ImmutableArray<EazyClientOptionsDefinition> options,
    bool nullableEnabled)
  {
    if (options.IsDefaultOrEmpty)
    {
      return;
    }

    foreach (var o in options)
    {
      GenerateClientsRegistration(context, o, nullableEnabled);
    }
  }

  private static void GenerateClientsRegistration(
    SourceProductionContext context,
    EazyClientOptionsDefinition options,
    bool nullableEnabled)
  {
    var code = $$"""
      {{AutoGeneratedComment}}
      {{nullableEnabled.ToNullableDirectiveIfEnabled()}}
      
      {{GetUsings(options)}}
      
      namespace {{options.NamespacePrefix}};

      public static class EazyHttpDiRegistration
      {
        public static IServiceCollection AddEazyHttpClients(this IServiceCollection services)
        {
          {{GetClientsRegistrations(options)}}

          return services;
        }
      }
      """;

    context.AddSource(
      options.GetDiRegistrationFilename(),
      code.GetFormattedCode());
  }

  private static string GetClientsRegistrations(
    EazyClientOptionsDefinition options)
  {
    var sb = new StringBuilder();

    foreach (var client in options.Clients)
    {
      var handlerSb = new StringBuilder();

      sb.AppendLine("services");
      
      sb.AppendLine(
        $".AddHttpClient<I{client.Name}, {client.Name}>(\"{client.Name}\")");

      if (options.HttpClientHandlers.TryGetValue(
        client.Name,
        out var handlerRawExpr))
      {
        var handlerName = handlerRawExpr
          .TryGetHandlerTypeName();

        handlerSb.AppendLine(
          $".ConfigurePrimaryHttpMessageHandler<{handlerName}>();");

        handlerSb.AppendLine("services");

        handlerSb.AppendLine(
          $".AddTransient<{handlerName}>()");
      }

      sb.AppendLine($"{handlerSb};");
    }

    return sb.ToString();
  }

  private static string GetUsings(EazyClientOptionsDefinition options)
  {
    string[] namespaces =
    [
      "Microsoft.Extensions.DependencyInjection",
      options
        .NamespacePrefix
        .GetEazyHttpClientNamespace()
    ];

    var sb = new StringBuilder();

    foreach (var ns in namespaces.OrderBy(x => x))
    {
      sb.AppendLine($"using {ns};");
    }

    return sb.ToString();
  }
}
