using System.Security.Cryptography.X509Certificates;

namespace EazyHttp.Generator.Generators;

[Generator]
internal sealed class HttpClientGenerator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.DefaultSourceOutputRegistration(Execute);
  }

  private static void Execute(
    SourceProductionContext context,
    ImmutableArray<EazyClientOptionsDefinition> options,
    bool nullableEnabled)
  {
    if (options.IsDefaultOrEmpty)
    {
      return;
    }
    
    foreach (var o in options)
    {
      GenerateClients(context, o, nullableEnabled);
    }
  }

  private static void GenerateClients(
    SourceProductionContext context,
    EazyClientOptionsDefinition options,
    bool nullableEnabled)
  {
    foreach (var client in options.Clients)
    {
      GenerateClient(
        context, 
        client, 
        options,
        nullableEnabled);
    }
  }

  private static void GenerateClient(
    SourceProductionContext context,
    HttpClientDefinition definition,
    EazyClientOptionsDefinition options,
    bool nullableEnabled)
  {
    var @namespace = options
      .NamespacePrefix
      .GetEazyHttpClientNamespace();

    var interfaceBase = definition.OptionalHeadersInMethods
      ? nameof(IEazyHttpClient)
      : nameof(ISimpleEazyHttpClient);

    var interfaceMethods = definition.OptionalHeadersInMethods
      ? GetFullInterfaceImplementation(nullableEnabled)
      : GetSimpleInterfaceImplementation(nullableEnabled);

    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      {{AutoGeneratedComment}}
      {{nullableEnabled.ToNullableDirectiveIfEnabled()}}

      {{GetUsings()}}

      namespace {{@namespace}};

      {{GeneratedCodeAttribute}}
      public interface I{{definition.Name}} : {{interfaceBase}};

      {{GeneratedCodeAttribute}}
      internal sealed class {{definition.Name}} : I{{definition.Name}}
      {
        private readonly {{nameof(EazyClientOptions)}} _options;
        private readonly IServiceProvider _serviceProvider;
        private readonly JsonSerializerOptions _serializerOptions;
        private readonly Encoding _encoding;
        private readonly RetryConfiguration{{nullable}} _retryConfiguration;

        public HttpClient HttpClient { get; }
          
        public {{definition.Name}}(
          HttpClient httpClient,
          IOptions<{{nameof(EazyClientOptions)}}> options,
          IServiceProvider serviceProvider)
        {
          HttpClient = httpClient;
          _options = options.Value;
          _serviceProvider = serviceProvider;

          {{GetBaseAddressInitializer(definition)}}

          var context = new ClientContext(
            nameof({{definition.Name}}), 
            serviceProvider);

          _encoding = ResolveEncoding(context, _options);
          _serializerOptions = ResolveSerializer(context, _options);
          var headers = ResolveHeaders(context, _options);
          _retryConfiguration = ResolveRetry(context, _options);

          foreach (var header in headers)
          {
            HttpClient
              .DefaultRequestHeaders
              .TryAddWithoutValidation(header.Name, header.Value);
          }
        }

        {{interfaceMethods}}

        {{GetResolverMethods(nullableEnabled)}}

        {{GetBuildUrl(nullableEnabled)}}

        {{GetDeserializer(nullableEnabled)}}

        {{GetSendCore(nullableEnabled)}}

        {{GetSendNoResult(nullableEnabled)}}

        {{GetSendAndDeserialize(nullableEnabled)}}

        {{GetSendEnvelope(nullableEnabled)}}

        private sealed record RawResponse(
          HttpStatusCode StatusCode,
          HttpResponseHeaders Headers,
          HttpContentHeaders ContentHeaders,
          byte[] ContentBytes,
          bool IsSuccessStatusCode);
      }
      """;


    context.AddSource(
      definition.GetEazyHttpClientFilename(@namespace),
      code.GetFormattedCode());
  }

  private static string GetUsings()
  {
    string[] namespaces =
    [
      "System",
      "System.Net.Http",
      $"{nameof(EazyHttp)}.{nameof(Contracts)}",
      $"{nameof(EazyHttp)}.{nameof(Configuration)}",
      "Microsoft.Extensions.Options",
      "System.Threading",
      "System.Threading.Tasks",
      "System.Collections.Generic",
      "System.Text",
      "System.Text.Json",
      "System.Collections.Immutable",
      $"{nameof(EazyHttp)}.Runtime",
      "System.IO",
      "System.Net",
      "System.Net.Http.Headers",
      $"{nameof(EazyHttp)}.{nameof(EazyHttp.Exceptions)}"
    ];
    
    var sb = new StringBuilder();

    foreach (var ns in namespaces.OrderBy(x => x))
    {
      sb.AppendLine($"using {ns};");
    }

    return sb.ToString();
  }

  private static string GetFullInterfaceImplementation(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code =
      $$"""
      // GET
      public async Task<TResult{{nullable}}> GetAsync<TResult>(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Get, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> GetWithResponseAsync<TResult>(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Get, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task GetAsync(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        await SendNoResultAsync(HttpMethod.Get, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // PUT
      public async Task<TResult{{nullable}}> PutAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Put, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PutWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Put, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task PutAsync(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Put, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // POST
      public async Task<TResult{{nullable}}> PostAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostAsync(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // DELETE
      public async Task<TResult{{nullable}}> DeleteAsync<TResult>(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Delete, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> DeleteWithResponseAsync<TResult>(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Delete, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task DeleteAsync(string route, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        await SendNoResultAsync(HttpMethod.Delete, route, query, null, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // PATCH
      public async Task<TResult{{nullable}}> PatchAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Patch, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PatchWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Patch, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task PatchAsync(string route, object body, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Patch, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // POST multipart/form-data
      public async Task<TResult{{nullable}}> PostFormAsync<TResult>(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostFormWithResponseAsync<TResult>(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostFormAsync(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        await SendNoResultAsync(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      // POST application/x-www-form-urlencoded
      public async Task<TResult{{nullable}}> PostUrlEncodedFormAsync<TResult>(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostUrlEncodedFormWithResponseAsync<TResult>(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostUrlEncodedFormAsync(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, IEnumerable<RequestHeader>{{nullable}} additionalHeaders = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        await SendNoResultAsync(HttpMethod.Post, route, query, content, additionalHeaders, cancellationToken).ConfigureAwait(false);
      }
      """;

    return code;
  }

  private static string GetSimpleInterfaceImplementation(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code =
      $$"""
      public async Task<TResult{{nullable}}> GetAsync<TResult>(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var result = await SendAndDeserializeAsync<TResult>(HttpMethod.Get, route, query, null, null, cancellationToken).ConfigureAwait(false);
        return result;
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> GetWithResponseAsync<TResult>(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var result = await SendAndEnvelopeAsync<TResult>(HttpMethod.Get, route, query, null, null, cancellationToken).ConfigureAwait(false);
        return result;
      }

      public async Task GetAsync(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        await SendNoResultAsync(HttpMethod.Get, route, query, null, null, cancellationToken).ConfigureAwait(false);
      }

      // PUT
      public async Task<TResult{{nullable}}> PutAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Put, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PutWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Put, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task PutAsync(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Put, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      // POST
      public async Task<TResult{{nullable}}> PostAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostAsync(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      // DELETE
      public async Task<TResult{{nullable}}> DeleteAsync<TResult>(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Delete, route, query, null, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> DeleteWithResponseAsync<TResult>(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Delete, route, query, null, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task DeleteAsync(string route, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        await SendNoResultAsync(HttpMethod.Delete, route, query, null, null, cancellationToken).ConfigureAwait(false);
      }

      // PATCH
      public async Task<TResult{{nullable}}> PatchAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Patch, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PatchWithResponseAsync<TResult>(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Patch, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task PatchAsync(string route, object body, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new StringContent(JsonSerializer.Serialize(body, _serializerOptions), _encoding, "application/json");
        await SendNoResultAsync(HttpMethod.Patch, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      // POST multipart/form-data
      public async Task<TResult{{nullable}}> PostFormAsync<TResult>(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostFormWithResponseAsync<TResult>(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostFormAsync(string route, IEnumerable<FormElement> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new MultipartFormDataContent();
        foreach (var el in elements)
        {
          if (el.FileName != null)
          {
            content.Add(el.HttpElementContent, el.QueryParam, el.FileName);
          }
          else
          {
            content.Add(el.HttpElementContent, el.QueryParam);
          }
        }
        await SendNoResultAsync(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      // POST application/x-www-form-urlencoded
      public async Task<TResult{{nullable}}> PostUrlEncodedFormAsync<TResult>(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        return await SendAndDeserializeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task<ResponseEnvelope<TResult{{nullable}}>> PostUrlEncodedFormWithResponseAsync<TResult>(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        return await SendAndEnvelopeAsync<TResult>(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }

      public async Task PostUrlEncodedFormAsync(string route, IEnumerable<KeyValuePair<string, string{{nullable}}>> elements, HttpQuery{{nullable}} query = null, CancellationToken cancellationToken = default)
      {
        var content = new FormUrlEncodedContent(elements);
        await SendNoResultAsync(HttpMethod.Post, route, query, content, null, cancellationToken).ConfigureAwait(false);
      }
      """;

    return code;
  }

  private static string GetBaseAddressInitializer(
    HttpClientDefinition definition)
  {
    if (string.IsNullOrWhiteSpace(definition.BaseAddress))
    {
      return "";
    }

    var code =
      $$"""
      if (!string.IsNullOrWhiteSpace({{definition.BaseAddress}}))
        {
          HttpClient.BaseAddress = new Uri({{definition.BaseAddress}});
        }
      """;

    return code;
  }

  private static string GetResolverMethods(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private static Encoding ResolveEncoding(
        ClientContext context,
        EazyClientOptions options)
      {
        // 1. Fixed per-client encoding
        if (options.Encodings.TryGetValue(context.ClientName, out var encoding))
        {
          return encoding;
        }

        // 2. Resolver fallback
        if (options.ResolveEncoding is { } resolver)
        {
          var resolved = resolver(context);
          if (resolved is not null)
          {
            return resolved;
          }
        }

        // 3. Default
        return Encoding.UTF8;
      }

      private static JsonSerializerOptions ResolveSerializer(
        ClientContext context,
        EazyClientOptions options)
      {
        // 1. Fixed per-client serializer
        if (options.SerializerOptions.TryGetValue(context.ClientName, out var serializer))
        {
          return serializer;
        }

        // 2. Resolver fallback
        if (options.ResolveSerializer is { } resolver)
        {
          var resolved = resolver(context);
          if (resolved is not null)
          {
            return resolved;
          }
        }

        // 3. Default
        return new JsonSerializerOptions(JsonSerializerDefaults.Web)
        {
          PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };
      }

      private static ImmutableArray<RequestHeader> ResolveHeaders(
        ClientContext context,
        EazyClientOptions options)
      {
        // 1. Fixed per-client headers
        if (options.PersistentHeaders.TryGetValue(context.ClientName, out var headers) && headers is not null)
        {
          return [.. headers];
        }

        // 2. Resolver fallback
        if (options.ResolveHeaders is { } resolver)
        {
          var resolved = resolver(context);
          if (resolved is not null)
          {
            return [.. resolved];
          }
        }

        // 3. Default: empty
        return [];
      }

      private static RetryConfiguration{{nullable}} ResolveRetry(
        ClientContext context,
        EazyClientOptions options)
      {
        // 1. Fixed per-client retry-config
        if (options.Retries.TryGetValue(context.ClientName, out var cfg))
        {
          return cfg;
        }

        // 2. Resolver fallback
        if (options.ResolveRetry is { } resolver)
        {
          return resolver(context);
        }

        // 3. Default: no retry
        return null;
      }
      """;

    return code;
  }

  private static string GetBuildUrl(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private string BuildUrl(
        string route,
        HttpQuery{{nullable}} query = null)
      {
        // Absolute URL -> ignore BaseAddress
        if (!string.IsNullOrWhiteSpace(route) &&
          route.StartsWith("http", StringComparison.OrdinalIgnoreCase))
        {
          var absolute = route.Trim();

          return query is null
            ? absolute
            : absolute + query.ToString();
        }

        var baseUrl = $"{HttpClient.BaseAddress}";

        if (!string.IsNullOrWhiteSpace(baseUrl))
        {
          baseUrl = baseUrl.TrimEnd('/');
        }

        route ??= string.Empty;
        route = route.TrimStart('/');

        var url = string.IsNullOrWhiteSpace(baseUrl)
          ? route
          : $"{baseUrl}/{route}";

        if (query is not null)
        {
          url += query.ToString();
        }

        return url;
      }
      """;

    return code;
  }

  private static string GetDeserializer(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private TResult{{nullable}} DeserializeBody<TResult>(RawResponse raw)
      {
        if (raw.ContentBytes is null ||
          raw.ContentBytes.Length == 0)
        {
          return default;
        }

        var mediaType = raw
          .ContentHeaders
          .ContentType?
          .MediaType;

        // JSON branch
        if (!string.IsNullOrWhiteSpace(mediaType) &&
          mediaType.Contains("json", StringComparison.OrdinalIgnoreCase))
        {
          return JsonSerializer.Deserialize<TResult>(
            raw.ContentBytes,
            _serializerOptions);
        }

        // Non-JSON branch: support string / byte[] / Stream
        var targetType = typeof(TResult);

        if (targetType == typeof(string))
        {
          var text = _encoding.GetString(raw.ContentBytes);
          return (TResult{{nullable}})(object)text;
        }

        if (targetType == typeof(byte[]))
        {
          return (TResult{{nullable}})(object)raw.ContentBytes;
        }

        if (targetType == typeof(Stream))
        {
          var ms = new MemoryStream(raw.ContentBytes, writable: false);
          return (TResult{{nullable}})(object)ms;
        }

        throw new ByteArrayExpectedException(
          $"Response content type '{mediaType ?? "unknown"}' is not JSON, " +
          $"and type '{targetType}' is not supported. " +
          $"Use '{nameof(String)}', '{nameof(Byte)}[]' or '{nameof(Stream)}' " +
          $"for non-JSON responses.");
      }
      """;

    return code;
  }

  private static string GetSendCore(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private async Task<RawResponse> SendCoreAsync(
        HttpMethod method,
        string route,
        HttpQuery{{nullable}} query,
        HttpContent{{nullable}} content,
        IEnumerable<RequestHeader>{{nullable}} additionalHeaders,
        CancellationToken cancellationToken)
      {
        var url = BuildUrl(route, query);

        using var request = new HttpRequestMessage(method, url)
        {
          Content = content
        };

        // Per-call headers
        if (additionalHeaders is not null)
        {
          foreach (var header in additionalHeaders)
          {
            if (string.IsNullOrWhiteSpace(header.Name))
            {
              continue;
            }

           var value = header.Value ?? string.Empty;

            request.Headers.TryAddWithoutValidation(header.Name, value);
          }
        }

        using var response = await HttpRetryExecutor
          .ExecuteAsync(
            HttpClient,
            request,
            _retryConfiguration,
            cancellationToken)
          .ConfigureAwait(false);

        byte[] contentBytes = [];

        if (response.Content is not null)
        {
          contentBytes = await response
            .Content
            .ReadAsByteArrayAsync(cancellationToken)
            .ConfigureAwait(false);
        }

        // Ensure we always have some HttpContentHeaders instance
        var contentHeaders = response.Content?.Headers
          ?? new ByteArrayContent([]).Headers;

        return new RawResponse(
          response.StatusCode,
          response.Headers,
          contentHeaders,
          contentBytes,
          response.IsSuccessStatusCode);
      }
      """;

    return code;
  }

  private static string GetSendAndDeserialize(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private async Task<TResult{{nullable}}> SendAndDeserializeAsync<TResult>(
        HttpMethod method,
        string route,
        HttpQuery{{nullable}} query,
        HttpContent{{nullable}} content,
        IEnumerable<RequestHeader>{{nullable}} additionalHeaders,
        CancellationToken cancellationToken)
      {
        var raw = await SendCoreAsync(
          method,
          route,
          query,
          content,
          additionalHeaders,
          cancellationToken)
          .ConfigureAwait(false);

        if (!raw.IsSuccessStatusCode)
        {
          var responseText = raw.ContentBytes.Length == 0
            ? string.Empty
            : _encoding.GetString(raw.ContentBytes);

          throw new FailedRequestException(
            raw.StatusCode,
            method,
            $"Request to '{route}' failed with status code {(int)raw.StatusCode} ({raw.StatusCode}).",
            responseText);
        }

        return DeserializeBody<TResult>(raw);
      }
      """;
    return code;
  }
  
  private static string GetSendEnvelope(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private async Task<ResponseEnvelope<TResult{{nullable}}>> SendAndEnvelopeAsync<TResult>(
        HttpMethod method,
        string route,
        HttpQuery{{nullable}} query,
        HttpContent{{nullable}} content,
        IEnumerable<RequestHeader>{{nullable}} additionalHeaders,
        CancellationToken cancellationToken)
      {
        var raw = await SendCoreAsync(
            method,
            route,
            query,
            content,
            additionalHeaders,
            cancellationToken)
          .ConfigureAwait(false);

        TResult{{nullable}} body = default;
        string{{nullable}} deserializationErrorMessage = null;

        if (raw.ContentBytes.Length > 0)
        {
          try
          {
            body = DeserializeBody<TResult>(raw);
          }
          catch (Exception ex)
          {
            deserializationErrorMessage = ex.Message;
          }
        }

        var envelope = new ResponseEnvelope<TResult{{nullable}}>(
          body,
          raw.ContentBytes,
          raw.StatusCode,
          raw.Headers,
          raw.ContentHeaders,
          raw.IsSuccessStatusCode);

        if (!string.IsNullOrWhiteSpace(deserializationErrorMessage))
        {
          envelope.DeserializationErrorMessage = deserializationErrorMessage;
        }

        return envelope;
      }
      """;
    return code;
  }

  private static string GetSendNoResult(bool nullableEnabled)
  {
    var nullable = nullableEnabled
      ? "?"
      : "";

    var code = $$"""
      private async Task SendNoResultAsync(
        HttpMethod method,
        string route,
        HttpQuery{{nullable}} query,
        HttpContent{{nullable}} content,
        IEnumerable<RequestHeader>{{nullable}} additionalHeaders,
        CancellationToken cancellationToken)
      {
        var url = BuildUrl(route, query);

        using var request = new HttpRequestMessage(method, url)
        {
          Content = content
        };

        // Per-call headers
        if (additionalHeaders is not null)
        {
          foreach (var header in additionalHeaders)
          {
            if (string.IsNullOrWhiteSpace(header.Name))
            {
              continue;
            }

            var value = header.Value ?? string.Empty;

            request.Headers.TryAddWithoutValidation(header.Name, value);
          }
        }

        using var response = await HttpRetryExecutor
          .ExecuteAsync(
            HttpClient,
            request,
            _retryConfiguration,
            cancellationToken)
          .ConfigureAwait(false);

        if (!response.IsSuccessStatusCode)
        {
          byte[] bytes = [];

          if (response.Content is not null)
          {
            bytes = await response.Content
              .ReadAsByteArrayAsync(cancellationToken)
              .ConfigureAwait(false);
          }

          var text = bytes.Length == 0
            ? string.Empty
            : _encoding.GetString(bytes);

          throw new FailedRequestException(
            response.StatusCode,
            method,
            $"The HTTP request failed with status code {(int)response.StatusCode} ({response.StatusCode}).",
            text);
        }
      }
      """;

    return code;
  }
}
