using System.Reflection;

namespace EazyHttp.Generator;

internal static class Constants
{
  public static string ConfigureMethodName => "ConfigureEazyHttpClients";

  public static string Generated => "Generated";

  public static string Clients => "Clients";

  public static string DependencyInjection => "DependencyInjection";

  public static string AutoGeneratedComment =>
    $"// <auto-generated last-generation=\"{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC\" />";

  public static string GeneratedCodeAttribute =>
    $"[System.CodeDom.Compiler.GeneratedCodeAttribute(\"{nameof(EazyHttp)}\", \"{Assembly.GetExecutingAssembly().GetName().Version}\")]";
}
