global using EazyHttp.Generator.CsScript;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp.Scripting;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Scripting;
global using Microsoft.CodeAnalysis.Text;
global using System.Text;
global using System.Text.RegularExpressions;
global using Microsoft.CodeAnalysis.Scripting.Hosting;
global using System.Reflection;
global using static EazyHttp.Generator.Helpers.StatementsExtensions;
